### ISSUE TITLE
Media Player Not Recognizing Musicbee or Windows Media Player

### ISSUE THREAD

**Issue by carcasonne** [amnweb/yasb#26]
**Describe the bug**
I have just installed YASB and ran it. Everything works as expected, except for the media player not recognizing my music player called MusicBee. I also tried testing a bit more, and it does not recognize Windows Media Player either, I guess it has something to do with local files being played differently?

Works fine on Spotify and Youtube.

**To Reproduce**
1. Open up Music Bee or Windows Media Player (Legacy)
2. Play any sound file
3. There will be no media player in the yasb bar

**Expected behavior**
The media player will display the song being played by MusicBee.

**Screenshots**
Example of it not showing up in MusicBee: https://i.imgur.com/PqmOz3x.png
Example of it not showing up in windows media player: https://i.imgur.com/0UMNDd3.png
Example of it working with Spotify: https://i.imgur.com/1fZ4WYW.png

**Desktop (please complete the following information):**
 - OS: Windows 22631.4037
 - Browser: Firefox
 - YASB branch: Main
 - Python: 3.12.0

**Additional context**
Hope you can help me, if the problem is not too small to fix

**Comment by amnweb** [comment]
I think the problem is with those Apps themselves, it seems that the Windows Media API does not work with them. However, @thomasroodnl may be able to explain better.

**Comment by thomasroodnl** [comment]
Hi @carcasonne, sorry for the late response. Like @amnweb said, if something does not show up in the Windows Media API it is usually because the app itself is not publishing it. At least for MusicBee I could indeed confirm that it is not outputting the 'now playing' data to the Windows Media API by default. See e.g. this (older) thread: https://getmusicbee.com/forum/index.php?topic=21240.0. Herethey introduce a plugin to add this feature, though I tried it and it was quite bugged and did not give me the right info. 

A good way to check if the Windows API is receiving the data is to click on the volume icon in the Windows taskbar. At the top of the context menu it should show playing media (you can verify with Spotify/Youtube). If something is there but it is not in YASB, we can likely fix it. If nothing is there, I am afraid there is nothing we can do.

You could optionally open an issue with the respective apps to see if they can add the Windows Media API publishing in their app.

**Comment by carcasonne** [comment]
I see, thank you both for helping me and being patient when the problem was actually MusicBee's and not yours. 

Cheers!
