### ISSUE TITLE
Constant label length

### ISSUE THREAD

**Issue by rohanb1216** [amnweb/yasb#56]
**What is the request?.**
An option to make certain widgets have constant label length, or width

**Why is it useful?**
When a widget with constantly changing text is enabled, it often shifts other widgets around. A constant width would allow everything to stay in place.

**How could it be implemented?**
Padding output with whitespace when below the specified max length, or perhaps a label token to specify where to add said whitespaces

**Comment by amnweb** [comment]
You can use CSS properties like `max-width` for the widget, but can you tell me which widget is problematic here?

**Comment by rohanb1216** [comment]
The traffic widget is the specific one being slightly annoying by shifting everything around, forgot to mention it in the initial issue

**Comment by amnweb** [comment]
That's what I assumed, there was already discussion about that widget on Discord. The problem is if we limit the number of characters like keeping it always at 20 in the label and you have 0 KB/s, there will be too much dead space.
Maybe you can just try do it with CSS something like this

```
.traffic-widget {
    max-width: 150px;
    min-width: 150px;
}
```

also try play with pixels, maybe 150 pixels isn't enough or maybe it's too much

**Comment by rohanb1216** [comment]
Yeah min width did the job, thanks :)
